# -*- coding: utf-8 -*-
"""neurofive-ml-track_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1md-funi0TI5g2m_lBGiOWSPUoi3ncEiE

# Titanic Exploratory Data Analysis (EDA)

**Author:** Faizan Khan

## Project Objective
The goal of this project is to perform Exploratory Data Analysis (EDA) on the Titanic dataset to understand its structure, identify missing values, analyze different features, and discover patterns before applying any machine learning models.
"""

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("train.csv")

print("Dataset loaded successfully!")

df.head()

df.tail()

rows, columns = df.shape

print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

print(df.columns.tolist())

df.info()

df.describe()

df.describe(include="all")

df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

df.dtypes

numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

print(numerical_columns)

categorical_columns = df.select_dtypes(include=["object"]).columns

print(categorical_columns)

duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

df.nunique()

df.memory_usage(deep=True)

print("Dataset Shape:", df.shape)
print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

"""## Initial Findings

- The Titanic dataset contains **891 rows** and **12 columns**.
- The dataset has both numerical and categorical features.
- Some columns such as **Age**, **Cabin**, and **Embarked** contain missing values.
- **Cabin** has the highest number of missing values.
- No duplicate rows were found.
- This analysis provides a better understanding of the dataset before applying machine learning techniques.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set plot style
sns.set_style("whitegrid")

print("Visualization libraries imported successfully!")

missing = df.isnull().sum()

plt.figure(figsize=(10,5))
missing[missing > 0].sort_values(ascending=False).plot(kind="bar")

plt.title("Missing Values in Each Column")
plt.xlabel("Columns")
plt.ylabel("Number of Missing Values")

plt.show()

"""Observation:
Cabin has the highest number of missing values, followed by Age and Embarked.
"""

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Survived")

plt.title("Survival Count")

plt.show()

"""Observation:
More passengers died than survived.
"""

survival = df["Survived"].value_counts(normalize=True) * 100

print(survival)

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Sex")

plt.title("Gender Distribution")

plt.show()

"""Observation:
The dataset contains more male passengers than female passengers.
"""

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Pclass")

plt.title("Passenger Class Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["Age"], bins=30, kde=True)

plt.title("Age Distribution")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["Fare"], bins=30, kde=True)

plt.title("Fare Distribution")

plt.show()

plt.figure(figsize=(7,5))

sns.boxplot(x=df["Age"])

plt.title("Age Boxplot")

plt.show()

"""Observation:
There are some outliers in passenger ages.
"""

plt.figure(figsize=(7,5))

sns.boxplot(x=df["Fare"])

plt.title("Fare Boxplot")

plt.show()

plt.figure(figsize=(10,7))

numeric_df = df.select_dtypes(include="number")

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm",
    linewidths=0.5
)

plt.title("Correlation Heatmap")

plt.show()

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Sex", hue="Survived")

plt.title("Survival by Gender")

plt.show()

"""Observation:
Female passengers had a much higher survival rate than male passengers.
"""

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Pclass", hue="Survived")

plt.title("Survival by Passenger Class")

plt.show()

plt.figure(figsize=(6,4))

sns.countplot(data=df, x="Embarked")

plt.title("Embarked Distribution")

plt.show()

plt.figure(figsize=(7,4))

sns.countplot(data=df, x="Embarked", hue="Survived")

plt.title("Survival by Embarked")

plt.show()

plt.figure(figsize=(8,4))

sns.countplot(data=df, x="SibSp", hue="Survived")

plt.title("Survival by Number of Siblings/Spouses")

plt.show()

plt.figure(figsize=(8,4))

sns.countplot(data=df, x="Parch", hue="Survived")

plt.title("Survival by Parents/Children")

plt.show()

df.groupby("Pclass")["Fare"].mean()

df.groupby("Pclass")["Age"].mean()

df.groupby("Sex")["Survived"].mean() * 100

df.groupby("Pclass")["Survived"].mean() * 100

"""# Final Conclusion

After performing Exploratory Data Analysis on the Titanic dataset, several important insights were discovered:

- The dataset contains missing values, especially in the Cabin and Age columns.
- Female passengers had a significantly higher survival rate than male passengers.
- First-class passengers had a much better chance of survival than third-class passengers.
- Most passengers were between 20 and 40 years old.
- Fare distribution is highly skewed, with a few passengers paying very high fares.
- The dataset is suitable for machine learning after handling missing values and preprocessing categorical variables.
"""

